apiVersion: v1
kind: Secret
metadata:
  name: test-secret
  annotations:
    k8s-controller-lib.tnozicka.github.io/sync: "true"
type: kubernetes.io/tls
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJnRENDQVNlZ0F3SUJBZ0lRTFl0STFJb3BndTI4eDYra0I3WVdnekFLQmdncWhrak9QUVFEQWpBZU1Sd3cKR2dZRFZRUURFeE4wWlhOMExYTmxZM0psZEM1a1pXWmhkV3gwTUI0WERUSTFNREV3TVRBd01EQXdNRm9YRFRJMgpNREV3TVRBd01EQXdNRm93SGpFY01Cb0dBMVVFQXhNVGRHVnpkQzF6WldOeVpYUXVaR1ZtWVhWc2REQlpNQk1HCkJ5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEEwSUFCT3lBMC9wMlpsWkliV3llZ3FlRnl4NFR0a3pMcVY2ME5HcTQKR0ZndnNtbTRhZmtsbXBvMENWc1JYdDZRT1BkRDlFYTV0S0ZtQlBUU2hMNE54MVBqZDdLalJ6QkZNQTRHQTFVZApEd0VCL3dRRUF3SUhnREFUQmdOVkhTVUVEREFLQmdnckJnRUZCUWNEQVRBZUJnTlZIUkVFRnpBVmdoTjBaWE4wCkxYTmxZM0psZEM1a1pXWmhkV3gwTUFvR0NDcUdTTTQ5QkFNQ0EwY0FNRVFDSUJhSWUyUm5iZjhXY2RCOHduY0UKdi9oTVRuSUdUQ3phTjQ4WTQ3emtRWXVtQWlCMENSa0ZDV2N2VWlaL25NY0x4TnhzZjFlYzI5QmYrY2JDN3Y4dgo5VmVmcnc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  tls.key: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUNPMCtvK1Q3dGMrSzRlTjBydjl6VXY0bTdndzZXSWFyZWUzM3FkT043c01vQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFN0lEVCtuWm1Wa2h0Yko2Q3A0WExIaE8yVE11cFhyUTBhcmdZV0MreWFiaHArU1dhbWpRSgpXeEZlM3BBNDkwUDBScm0wb1dZRTlOS0V2ZzNIVStOM3NnPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
